# LOADING THE DATA & DATA PREPROCESSING
https://www.kaggle.com/vikrishnan/iris-dataset

In [89]:
import pandas as pd
import numpy as np

In [90]:
col_names = ['sepal length', 'sepal width','petal length','petal width','species']  ### assigning col names and loading data
df= pd.read_csv("iris.data.csv", names=col_names)

In [91]:
df.columns  ### check the columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width',
       'species'],
      dtype='object')

In [92]:
df.head() ### check 1st 5 data

sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [93]:
df.shape  ### no of rows and cols

(150, 5)

In [94]:
df.isna().sum()   ### check null value

sepal length    0
sepal width     0
petal length    0
petal width     0
species         0
dtype: int64

In [95]:
df.describe() ### get the min max and quartiles

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [96]:
df['species'] = df.species.astype('category').cat.codes   ###labeling 1,2,3

In [97]:
df["species"].unique()  ### we have three different species 

array([0, 1, 2], dtype=int8)

In [98]:
X = df.iloc[:, 0:4].values  ### y is the response variable x is the predictor variable
y = df.iloc[:, 4].values

# Dividing the data into train and test

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)     ###70% data in train set

In [100]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [101]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA     ####using only 1 component
lda = LDA(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [102]:
from sklearn.ensemble import RandomForestClassifier

class_ = RandomForestClassifier(max_depth=2)

class_.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [103]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[11  0  0]
 [ 0 16  1]
 [ 0  0 17]]
Accuracy0.9777777777777777
